version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: traffic_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - internal_network



  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal_network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - DOCKER_CONTAINER=True
  
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ENV=production
      - DOCKER_CONTAINER=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    networks:
      - internal_network

networks:
  internal_network:
